project:
  type: website
  output-dir: docs
  resources:
    - "data/"

website:
  title: "Research Methods in R"
  site-url: "https://bwurth.github.io/research-methods/"
  repo-url: https://github.com/bwurth/research-methods
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto