---
title: "Research Methods in R"
format: 
  html:
    theme: cosmo
    css: styles.css
    toc: true
---

## Welcome

This course serves as an introduction to research methods, providing students with a foundational understanding of how to conduct data analysis using the R programming language. Through hands-on practice, students will learn essential concepts such as data manipulation, statistical analysis, and visualisation, all of which are critical for conducting independent research. By the end of the course, students will be equipped with the skills needed to effectively apply quantitative methods in their dissertations, enabling them to analyse real-world data and draw meaningful insights for research in business and entrepreneurship and social sciences more broadly.

For more information, visit our public [GitHub repository](https://github.com/bwurth/research-methods).

## Course Outline

Click on the links below to access the lesson materials. Each lesson includes theory, examples, and practical exercises. We recommend that you work through the lessons in the given order and use the HTML versions, but the PDF files contain the same information.

0. **Getting Started** [ [html](00-getting-started/00-getting-started.html) | [pdf](00-getting-started/00-getting-started.pdf) ]

1. **Introduction** [ [html](01-introduction/01-introduction.html) | [pdf](01-introduction/01-introduction.pdf) ]

## University of Glasgow MGT4018 and MGT4090

This course covers all required materials and more for the University of Glasgow's third year courses MGT4018 and MGT4090 that prepare students for their dissertations. In addition to the general lessons and exercises above, the following tutorials cover the same exercises than the SPSS tutorials. If you have never used R before, please go through **00. Getting Started** and **01. Introduction** before starting with these labs. The video below will help you get started:

{{< video https://youtu.be/vXWU1X51yPA >}}

**Lab 1** [ [html](lab-uofg-01/lab-uofg-01.html) | [pdf](lab-uofg-01/lab-uofg-01.pdf) ]

**Lab 2** [ [html](lab-uofg-02/lab-uofg-02.html) | [pdf](lab-uofg-02/lab-uofg-02.pdf) ]

## Acknowledgements

This course and its materials are the culmination of many years of work and delivering a variety of classes around research methods and data science at the University of Strathclyde and the University of Glasgow. Some of the content in the earlier lessons is inspired by and adapted from teaching materials from Kate Pyper ([LinkedIn](https://www.linkedin.com/in/kate-pyper-86a50350/)) and the organisation and structure of this course have benefited from Grant McDermott's ([GitHub](https://github.com/grantmcdermott)) [EC 607 Data Science for Economists](https://github.com/uo-ec607/lectures) at the University of Oregon.

## License

This repository is licensed under two different licenses for different types of content:

1. **Code (MIT License)**: All R scripts, code snippets, and technical components of the course are licensed under the MIT License. You are free to use, copy, modify, merge, publish, distribute, sublicense, or sell copies of the code, as long as attribution is provided. See the [LICENSE-CODE](LICENSE-CODE) file for details.

2. **Course Materials (CC BY 4.0)**: All written content, lessons, quizzes, and educational materials in this repository are licensed under the Creative Commons Attribution 4.0 International License. You are free to share and adapt the materials, even for commercial purposes, as long as attribution is provided. See the [LICENSE-CONTENT](LICENSE-CONTENT) file for details.
